---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php for CentOS
    package:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
